steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_AR_REPO}/$_SERVICE_NAME:$COMMIT_SHA', '.' ]
    dir: backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_AR_REPO}/$_SERVICE_NAME:$COMMIT_SHA' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=${_AR_REPO}/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --set-env-vars-file=.env
      - --port=8080
      - --memory=1Gi
      - --max-instances=3
      - --timeout=300
      - --cpu=1
      - --project=$PROJECT_ID
    dir: backend
substitutions:
  _AR_REPO: 'LOCATION-docker.pkg.dev/PROJECT_ID/REPO_NAME'
  _SERVICE_NAME: 'health-backend'
  _REGION: 'us-central1' 